### ISSUE TITLE
Audio Support?

### ISSUE THREAD

**Issue by theaccordance** [groupon/greenscreen#25]
Curious, is audio currently supported with Greenscreen?  I set up the nyan test channel and noticed the audio isn't coming through.

**Comment by ehzhang** [comment]
Unfortunately, audio isn't supported!

**Comment by theaccordance** [comment]
That is unfortunate!  Do you know if it's a technical limitation, or simply lack of support for the feature?

**Comment by doubleaa93** [comment]
Audio is working fine on my end. Just use a <audio> or even <video> tag. Audio comes out fine through the tv which is then routed to speakers

**Comment by theaccordance** [comment]
@doubleaa93, are you rendering a publicly available URL? If so, can you share so I can test?

**Comment by doubleaa93** [comment]
@theaccordance , Here is a jsfiddle with a audio tag point one of your channels to it and test if sound comes out fine. https://jsfiddle.net/6uxc2cpa/embedded/result/
It just uses html5 audio tags
