### ISSUE TITLE
Chromecast not added

### ISSUE THREAD

**Issue by benkoller** [groupon/greenscreen#28]
Hi,

I fear this might be a duplicate of #19  and #12 - If yes please close accordingly and excuse the dupe.

The situation is the following: Chromecast has been added to Dev console successfully, App has been created and ID has been entered correctly to the gscreen-config.js. I can access said Chromecasts through the desktop & android apps and share content to it using the addons f/ android & chrome.

It has been over 72h now since I first registered the Chromecast.

Whenever I access localhost:4994/chromecasts I do not see the "Add"-button, if I go to /chromecasts/new manually the name field stays inactive even though I can clearly see the Chromecast being connected to my network.

NPM does not log any errors whatsoever, neither does couchdb. I can add channels without issues.

Is there a logging option hidden to me that I could use to track down the issue further? Might it be a communication problem between npm and the Cast App that I was so far unable to figure out? 

Due to these issues I can't access the debugging of the Chromecast to track this down further.

Any help appreciated.

**Comment by theaccordance** [comment]
I've experienced this myself and believe the problem resides with one of the following:
- CastAway (third-party wrapper to talk to Google Cast's Sender API)
- Chromecast Extension
- Computer/Network configuration

**Comment by benkoller** [comment]
Completely redoing everything from scratch fixed the issue. Somewhere along the way a mistake must have happened.
