### ISSUE TITLE
Channels always display a GRAY screen

### ISSUE THREAD

**Issue by xBau** [groupon/greenscreen#31]
Greenscreen is running perfectly:
- I could run the server
- I could add my chromecasts
- I could add my channels
- I could send alerts to my chromecasts

BUT, my chromecasts always display a gray screen. If I change the channel for the chromecast I see the green screen for a second and the returns the gray screen.

Things to consider:
- If a send an alert it appears well above the gray screen.
- When I click on the chromecast preview link to see the channel in the browser I see the gray screen aswell.

Any idea?
Thank you very much!

**Comment by ehzhang** [comment]
Greenscreen uses iframes to display content. Sometimes, certain websites (like google.com) do not allow iframe content to appear that is not from the same origin.

'forbidden by X-Frame-Options'

**Comment by xBau** [comment]
Yeah! That was the problem :)

Thank you ehzhang!
