### ISSUE TITLE
Stupid Noob question... where do I place the gscreen files on a mac?

### ISSUE THREAD

**Issue by davidcatherall** [groupon/greenscreen#46]

**Comment by tobefound** [comment]
You could place them anywhere as the directory is a self-contained webserver thru node.

**Comment by davidcatherall** [comment]
Thanks, I'll have a look around - completely new to Node, couchdb, Mac et al.  Got it running (sort of) on windows but desperately trying to sort it on Mac.  Thanks for your response, it's much appreciated.
