### ISSUE TITLE
New Chromecast - problem adding

### ISSUE THREAD

**Issue by davidcatherall** [groupon/greenscreen#47]
Hi, When 'Add a Chromecast' is chosen the 'Add new Chromecast screen appears but nothing will populate the 'Name' field. Any tips?

**Comment by joshstrange** [comment]
@davidcatherall I'm having the same problem. I've setup greenscreen with success before but now I can't seem to get the name field to populate. I've tracked it down to the fact that castAway.connect() never seems to be firing after selecting a chromecast....

**Comment by joshstrange** [comment]
I just looked at the castAway library they are using and it's identical to the newest version on github and I can't find any issues filed over on that library that would indicate that it's no longer working... Still digging...

**Comment by joshstrange** [comment]
So the success handler for CastAway.requestSession is never being fired even after correctly picking a chromecast from the list. I'm looking for changelogs for google's chromecast JS api to see if I can pinpoint a reason.

**Comment by joshstrange** [comment]
Ok I tested in 42 and it's still not working. It could be the chrome extension itself has changed which I don't know how to get an older version of that. I'm going to read some docs on the JS API to see if the CastAway library needs changes

**Comment by joshstrange** [comment]
It appears that google's core API call chrome.cast.requestSession isn't working... It pops the chromecast picker but even after connect it NEVER calls the error or success callback. I can't for the life of me figure out why this is...

**Comment by joshstrange** [comment]
Ok so I tried swapping out my AppId for one of google's and the callback was fired. There has to be something wrong with my AppId. It's not published but I've added all of my chromecasts to my account and done all of the checks needed (reboot, factory reset, check for offers, etc). Still investigating...

**Comment by joshstrange** [comment]
Son of a.... So after a factory reset, another check for offers, and a reboot I can add it... I feel like an idiot as I even identified this as the problem in another issue on here... I must have done something in the wrong order...

**Comment by joshstrange** [comment]
However now the "about to cast" icon is all that is displayed...

**Comment by joshstrange** [comment]
I just deleted my last two comments, the problem is not resolved and there appears to be an issue with my AppId (yes all the chromecasts are registered). I probably won't have more time to look at this until later this week.

**Comment by davidcatherall** [comment]
@joshstrange 
Success!  I re-did steps and all is now OK.

**Comment by joshstrange** [comment]
@davidcatherall When you said you "re-did steps" can you outline those steps? I just re-tested this morning and it still doesn't work for me.

**Comment by davidcatherall** [comment]
@joshstrange  Everything as in the set-up guide.  I didn't anything more. I run it on OS X (El Capitan)  run couchdb from 1 terminal and NPM start from a separate terminal, launch Chrome and browse to the localhost:4994 page.  Add Chromecast and the API opens the chromecast add-in.  Works fine now - though It's taken me 4 attempts.  WIndows, Linux and Mac twice.  Always the same issue until this time around.  I have the url to setup-chromecast poining to my local machines IP address in both the receiver details and sender details in the SDK console though I don't know if the sender one is required.  Nothing else done differently. I hope you get it sorted soon as I know how frustrating it is.  I'll have another look over it tomorrow - If I spot anything obvious I'll let you know.

**Comment by davidcatherall** [comment]
@joshstrange - Weirdly enough... I've just run up the windows version I installed (my first attempt from a couple of months ago) and it's bloody working here now too!

**Comment by joshstrange** [comment]
@davidcatherall Are you using the same AppId or did you generate a new one?

**Comment by davidcatherall** [comment]
I generated a new one. But I'm using the old one!
